# Generated by Django 5.1.3 on 2025-04-06 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autosavecode",
            name="problem",
            field=models.ForeignKey(
                db_column="problem_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.problem",
            ),
        ),
        migrations.RenameField(
            model_name="autosavecode",
            old_name="problem",
            new_name="problem_id",
        ),
        migrations.AlterField(
            model_name="autosavecode",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="autosavecode",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="problem",
            field=models.ForeignKey(
                db_column="problem_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.problem",
            ),
        ),
        migrations.RenameField(
            model_name="conversationsession",
            old_name="problem",
            new_name="problem_id",
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="conversationsession",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="recommendation",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="userattribute",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="problem",
            field=models.ForeignKey(
                db_column="problem_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.problem",
            ),
        ),
        migrations.RenameField(
            model_name="userhistory",
            old_name="problem",
            new_name="problem_id",
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="userhistory",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="usertopicmastery",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="usertopicmastery",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="problem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
