# Generated by Django 5.1.3 on 2025-04-16 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userhistory_feedback_userhistory_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_sim", models.FloatField()),
                ("score_common", models.FloatField()),
                ("score_diff", models.FloatField()),
                ("score_knowledge", models.FloatField()),
                ("score_interest", models.FloatField()),
                ("score_path", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        db_column="problem_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="users.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Log",
                "verbose_name_plural": "Recommendation Logs",
                "db_table": "recommendation_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="UserRecommendationWeight",
        ),
    ]
