# 全局 topic 列表
ALL_TOPICS = [
    "Array",
    "String",
    "Linked List",
    "Stack",
    "Queue",
    "Hash Table",
    "Recursion",
    "Binary Search",
    "Bit Manipulation",
    "Greedy",
    "Dynamic Programming",
    "Tree",
    "Binary Search Tree",
    "Segment Tree",
    "Trie",
    "Backtracking",
    "Bash Scripting",
    "SQL",
    "SQL Schema",
    "Rejection Sampling",
    "Geometry",
    "Random",
    "Reservoir Sampling",
    "Database Design",
    "Database",
    "Line Sweep",
    "Multithreading",
    "Suffix Array",
    "Thread Synchronization",
    "Calendar",
    "Rolling Hash",
    "Database Management",
    "Database design",
    "SQL Queries",
    "Probability Calculation",
    "SQL Query",
    "OOP",
    "Minimax",
    "Schema",
    "Memoization",
    "String Manipulation",
    "Regular Expression",
    "File Handling",
    "Math",
    "Two Pointers",
    "Depth-first Search",
    "Divide and Conquer",
    "Heap",
    "Ordered Map",
    "Sort",
    "Sliding Window",
    "Breadth-first Search",
    "Union Find",
    "Graph",
    "Dequeue",
    "Topological Sort",
    "Binary Indexed Tree",
    "Brainteaser",
    "Design",
    "Meet in the Middle",
]