# Generated by Django 5.1.3 on 2025-04-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_autosavecode_problem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_topics",
                        to="users.problem",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_problems",
                        to="users.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Problem",
                "verbose_name_plural": "Topic Problems",
                "db_table": "topic_problems",
                "unique_together": {("topic", "problem")},
            },
        ),
    ]
