# Generated by Django 5.1.3 on 2025-04-10 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_topicproblem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecommendationWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_weight", models.FloatField(default=1.0)),
                ("common_topics_weight", models.FloatField(default=1.0)),
                ("difficulty_weight", models.FloatField(default=1.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_weights",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Recommendation Weight",
                "verbose_name_plural": "User Recommendation Weights",
                "db_table": "user_recommendation_weights",
            },
        ),
    ]
