# Generated by Django 5.1.3 on 2025-04-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userrecommendationweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userhistory",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
